name       : maxima
version    : '5.42'
release    : 4
source     :
    - https://sourceforge.net/projects/maxima/files/Maxima-source/5.42.0-source/maxima-5.42.0.tar.gz : d65fea937d99d251808e48e23130edd090af1fc6456312493e8b2fb6616cb734
license    : GPL-2.0-or-later
component  : office.maths
summary    : A Computer Algebra System
description: |
    Maxima is a system for the manipulation of symbolic and numerical expressions, including differentiation, integration, Taylor series, Laplace transforms, ordinary differential equations, systems of linear equations, polynomials, sets, lists, vectors, matrices and tensors. Maxima yields high precision numerical results by using exact fractions, arbitrary-precision integers and variable-precision floating-point numbers. Maxima can plot functions and data in two and three dimensions.
builddeps  :
    - sbcl
rundeps    :
    - gnuplot
    - sbcl
setup      : |
    %configure --enable-sbcl
build      : |
    %make
install    : |
    %make_install
