name       : maxima
version    : 5.41.0
release    : 2
source     :
    - https://sourceforge.net/projects/maxima/files/Maxima-source/5.41.0-source/maxima-5.41.0.tar.gz : daf8254600f4c7d9f079a0084178aaf036bd97a63b1e77b945f4120d7e401674
license    : GPL-2.0
component  : office.maths
summary    : A Computer Algebra System
description: |
    Maxima is a system for the manipulation of symbolic and numerical expressions, including differentiation, integration, Taylor series, Laplace transforms, ordinary differential equations, systems of linear equations, polynomials, sets, lists, vectors, matrices and tensors. Maxima yields high precision numerical results by using exact fractions, arbitrary-precision integers and variable-precision floating-point numbers. Maxima can plot functions and data in two and three dimensions.
builddeps  :
    - sbcl
rundeps    :
    - gnuplot
    - sbcl
setup      : |
    %configure --enable-sbcl
build      : |
    %make
install    : |
    %make_install
