name       : maxima
version    : 5.42.1
release    : 5
source     :
    - https://netix.dl.sourceforge.net/project/maxima/Maxima-source/5.42.1-source/maxima-5.42.1.tar.gz : 8f555aec33bc61b5a3ee0fe2e9d6c1179db67a2ff7e0eceb6bb614058eeb40cd
license    : GPL-2.0-or-later
component  : office.maths
summary    : A Computer Algebra System
description: |
    Maxima is a system for the manipulation of symbolic and numerical expressions, including differentiation, integration, Taylor series, Laplace transforms, ordinary differential equations, systems of linear equations, polynomials, sets, lists, vectors, matrices and tensors. Maxima yields high precision numerical results by using exact fractions, arbitrary-precision integers and variable-precision floating-point numbers. Maxima can plot functions and data in two and three dimensions.
builddeps  :
    - sbcl
rundeps    :
    - gnuplot
    - sbcl
setup      : |
    %configure --enable-sbcl
build      : |
    %make
install    : |
    %make_install
